-- cv-entries.seed.sql
-- ===========================================================================
--
-- ⚠️ GENERATED by `node cv-seed.mjs` from `cv-entries.js`. Do not hand-edit:
-- an edit here is invisible to `cv.test.js` (which reads the JS) and the next
-- run of the generator discards it without saying so.
--
-- Every string below is verbatim from `JobSearch/cv_2026.tex` (1 Sep 2026).
-- Nothing was written by a model. `tags`, `sort` and `pinned` are the only
-- additions, and they are metadata ABOUT the entries rather than claims made by
-- them.
--
-- Apply `supabase/migrations/20260908120000_job_cv_entries.sql` first; this
-- file only fills the table.
--
-- `do update` rather than `do nothing` — unlike `modules.seed.sql`, the
-- source of truth for these rows is the committed `cv-entries.js`, so re-running
-- must reconcile the table with the repo rather than silently no-op. See the
-- header of `cv-seed.mjs`.

insert into public.job_cv_entries
  (user_id, name, section, title, meta, org, dates, status,
   bullets, data, tags, lang, pinned, enabled, sort)
values
  (
    'a33625c2-4dd2-44fa-b2e5-4d455eeac59d',
    $cv$contact_main$cv$,
    $cv$contact$cv$,
    $cv$Bastian Rønfeldt Thomsen$cv$,
    null,
    null,
    null,
    null,
    '{}',
    $cv${"items":[{"icon":"map-marker-alt","text":"Copenhagen, Denmark"},{"icon":"phone","text":"+45 42 66 08 98","private":true},{"icon":"envelope","text":"Bastianrthomsen@gmail.com","url":"mailto:Bastianrthomsen@gmail.com"}],"links":[{"icon":"github","label":"github.com/Prk315","url":"https://github.com/Prk315"},{"icon":"linkedin","label":"LinkedIn","url":"https://www.linkedin.com/in/bastian-thomsen-167652205"},{"icon":"globe","label":"Portfolio","url":"https://prk315.github.io/personal-website/"}]}$cv$::jsonb,
    '{}',
    $cv$en$cv$,
    true,
    true,
    0
  ),
  (
    'a33625c2-4dd2-44fa-b2e5-4d455eeac59d',
    $cv$profile_main$cv$,
    $cv$profile$cv$,
    null,
    $cv$I build software end to end and run it in production on my own hardware, every day. A six-application desktop and mobile ecosystem on one Postgres schema; local LLM pipelines doing real classification work; reinforcement-learning agents whose policies export into Unreal Engine. Finishing a BSc in Machine Learning and Data Science at the University of Copenhagen, where I also teach the systems and performance course. I care most about the failure modes that only appear once something is really running.$cv$,
    null,
    null,
    null,
    array[$cv$Looking for: a team building something worth building — games, real-time systems, or applied AI$cv$],
    '{}'::jsonb,
    '{}',
    $cv$en$cv$,
    true,
    true,
    0
  ),
  (
    'a33625c2-4dd2-44fa-b2e5-4d455eeac59d',
    $cv$work_game_entities$cv$,
    $cv$work$cv$,
    $cv$Autonomous Game Entities$cv$,
    $cv$Rust, reinforcement learning, Unreal Engine$cv$,
    null,
    null,
    null,
    array[$cv$Simulation and RL training loop written from scratch in Rust; a quadrupedal rig learns locomotion from reward alone$cv$, $cv$Policies export into Unreal Engine through a pipeline built before the first agent ran, so a result can be reproduced rather than rescued from a checkpoint$cv$],
    '{}'::jsonb,
    array[$cv$rust$cv$, $cv$reinforcement$cv$, $cv$rl$cv$, $cv$unreal$cv$, $cv$gamedev$cv$, $cv$games$cv$, $cv$simulation$cv$, $cv$real-time$cv$, $cv$ai$cv$, $cv$ml$cv$],
    $cv$en$cv$,
    false,
    true,
    10
  ),
  (
    'a33625c2-4dd2-44fa-b2e5-4d455eeac59d',
    $cv$work_nexus$cv$,
    $cv$work$cv$,
    $cv$Nexus — Personal Software Ecosystem$cv$,
    $cv$Rust (Tauri 2), React 19, TypeScript, Supabase$cv$,
    null,
    null,
    null,
    array[$cv$Six interconnected desktop and mobile apps on one Postgres schema (~100 tables), one component library, one IPC layer — built solo, used daily$cv$, $cv$Row-level security scoped to auth.uid(), forward-only migrations against a database every branch shares, and trigger-maintained invariants where correctness cannot be left to the client$cv$, $cv$Real-time 3D graph view (three.js / react-three-fiber) with custom layout forces, debugged at the render loop: two THREE instances were corrupting simulation state every frame$cv$, $cv$Local LLM pipelines (Ollama + Qwen via n8n) doing production classification and extraction; the model returns a checkable verdict, never final prose$cv$],
    '{}'::jsonb,
    array[$cv$rust$cv$, $cv$tauri$cv$, $cv$react$cv$, $cv$typescript$cv$, $cv$supabase$cv$, $cv$postgres$cv$, $cv$postgresql$cv$, $cv$sql$cv$, $cv$fullstack$cv$, $cv$ios$cv$, $cv$swift$cv$, $cv$threejs$cv$, $cv$graphics$cv$, $cv$real-time$cv$, $cv$llm$cv$, $cv$ollama$cv$, $cv$n8n$cv$, $cv$rls$cv$, $cv$systems$cv$, $cv$backend$cv$, $cv$frontend$cv$],
    $cv$en$cv$,
    false,
    true,
    20
  ),
  (
    'a33625c2-4dd2-44fa-b2e5-4d455eeac59d',
    $cv$work_knowledge_graph$cv$,
    $cv$work$cv$,
    $cv$University Knowledge Graph$cv$,
    $cv$DAG, Markov chains, Kalman filters, local LLMs$cv$,
    null,
    null,
    null,
    array[$cv$Every concept across every course topologically sorted into a dependency DAG, producing linearised learning paths and a retention schedule — the target is recall months later, not first exposure$cv$],
    '{}'::jsonb,
    array[$cv$dag$cv$, $cv$markov$cv$, $cv$kalman$cv$, $cv$llm$cv$, $cv$algorithms$cv$, $cv$graph$cv$, $cv$data$cv$, $cv$ml$cv$, $cv$python$cv$],
    $cv$en$cv$,
    false,
    true,
    30
  ),
  (
    'a33625c2-4dd2-44fa-b2e5-4d455eeac59d',
    $cv$work_mirte_robot$cv$,
    $cv$work$cv$,
    $cv$MIRTE Robot$cv$,
    $cv$Robotics, computer vision, probabilistic state estimation$cv$,
    null,
    null,
    null,
    array[$cv$Extended the platform in software and hardware, designed probabilistic-first: state is a distribution, and a sensor reading updates belief rather than replacing it$cv$],
    '{}'::jsonb,
    array[$cv$robotics$cv$, $cv$computer vision$cv$, $cv$vision$cv$, $cv$probabilistic$cv$, $cv$estimation$cv$, $cv$sensors$cv$],
    $cv$en$cv$,
    false,
    true,
    40
  ),
  (
    'a33625c2-4dd2-44fa-b2e5-4d455eeac59d',
    $cv$exp_ku_instructor$cv$,
    $cv$experience$cv$,
    $cv$Instructor — High Performance Programming and Systems$cv$,
    null,
    $cv$University of Copenhagen$cv$,
    $cv$2026 – Present$cv$,
    null,
    array[$cv$Teach performance-oriented systems programming to undergraduates; appointed while still completing the degree$cv$],
    '{}'::jsonb,
    array[$cv$teaching$cv$, $cv$systems$cv$, $cv$performance$cv$, $cv$hpc$cv$, $cv$c$cv$],
    $cv$en$cv$,
    false,
    true,
    10
  ),
  (
    'a33625c2-4dd2-44fa-b2e5-4d455eeac59d',
    $cv$exp_armed_forces$cv$,
    $cv$experience$cv$,
    $cv$Engineer Company — Conscription$cv$,
    null,
    $cv$Danish Armed Forces$cv$,
    $cv$2022 – 2023$cv$,
    null,
    '{}',
    '{}'::jsonb,
    array[$cv$teamwork$cv$, $cv$leadership$cv$],
    $cv$en$cv$,
    false,
    true,
    20
  ),
  (
    'a33625c2-4dd2-44fa-b2e5-4d455eeac59d',
    $cv$edu_ku_bsc$cv$,
    $cv$education$cv$,
    $cv$BSc Machine Learning and Data Science$cv$,
    null,
    $cv$University of Copenhagen$cv$,
    $cv$2023 – 2026$cv$,
    $cv$In Progress$cv$,
    array[$cv$Current: Hybrid Quantum Programming | Robot Systems and Vision | Virtual Reality$cv$, $cv$Completed: Machine Learning A | High Performance Programming and Systems | Database Systems$cv$, $cv$Next: MSc in Quantum Information, or Artificial Intelligence and Robotics$cv$],
    '{}'::jsonb,
    array[$cv$ml$cv$, $cv$data$cv$, $cv$education$cv$],
    $cv$en$cv$,
    true,
    true,
    10
  ),
  (
    'a33625c2-4dd2-44fa-b2e5-4d455eeac59d',
    $cv$skills_languages$cv$,
    $cv$skills$cv$,
    $cv$Languages$cv$,
    $cv$Rust, TypeScript, Python, SQL, C, Swift, F#$cv$,
    null,
    null,
    null,
    '{}',
    '{}'::jsonb,
    array[$cv$rust$cv$, $cv$typescript$cv$, $cv$python$cv$, $cv$sql$cv$, $cv$c$cv$, $cv$swift$cv$, $cv$f#$cv$],
    $cv$en$cv$,
    true,
    true,
    10
  ),
  (
    'a33625c2-4dd2-44fa-b2e5-4d455eeac59d',
    $cv$skills_engines_graphics$cv$,
    $cv$skills$cv$,
    $cv$Engines & Graphics$cv$,
    $cv$Unreal Engine, three.js / WebGL, real-time rendering$cv$,
    null,
    null,
    null,
    '{}',
    '{}'::jsonb,
    array[$cv$unreal$cv$, $cv$threejs$cv$, $cv$webgl$cv$, $cv$graphics$cv$, $cv$real-time$cv$, $cv$rendering$cv$, $cv$gamedev$cv$],
    $cv$en$cv$,
    false,
    true,
    20
  ),
  (
    'a33625c2-4dd2-44fa-b2e5-4d455eeac59d',
    $cv$skills_ml_ai$cv$,
    $cv$skills$cv$,
    $cv$ML & AI$cv$,
    $cv$PyTorch, scikit-learn, reinforcement learning, local inference (Ollama, quantised models), pandas, NumPy$cv$,
    null,
    null,
    null,
    '{}',
    '{}'::jsonb,
    array[$cv$pytorch$cv$, $cv$ml$cv$, $cv$ai$cv$, $cv$reinforcement$cv$, $cv$ollama$cv$, $cv$llm$cv$, $cv$pandas$cv$, $cv$numpy$cv$, $cv$python$cv$],
    $cv$en$cv$,
    false,
    true,
    30
  ),
  (
    'a33625c2-4dd2-44fa-b2e5-4d455eeac59d',
    $cv$skills_systems_data$cv$,
    $cv$skills$cv$,
    $cv$Systems & Data$cv$,
    $cv$PostgreSQL / Supabase, Tauri, Docker, Git, REST APIs, n8n, ETL pipelines, row-level security design$cv$,
    null,
    null,
    null,
    '{}',
    '{}'::jsonb,
    array[$cv$postgresql$cv$, $cv$postgres$cv$, $cv$supabase$cv$, $cv$tauri$cv$, $cv$docker$cv$, $cv$git$cv$, $cv$rest$cv$, $cv$n8n$cv$, $cv$etl$cv$, $cv$rls$cv$, $cv$data$cv$, $cv$systems$cv$],
    $cv$en$cv$,
    false,
    true,
    40
  )
on conflict (user_id, lower(name)) do update set
  section = excluded.section,
  title   = excluded.title,
  meta    = excluded.meta,
  org     = excluded.org,
  dates   = excluded.dates,
  status  = excluded.status,
  bullets = excluded.bullets,
  data    = excluded.data,
  tags    = excluded.tags,
  lang    = excluded.lang,
  pinned  = excluded.pinned,
  enabled = excluded.enabled,
  sort    = excluded.sort;
