#!/usr/bin/env node
/**
 * Generate `cv-entries.seed.sql` from `cv-entries.js`.
 *
 *   node cv-seed.mjs            # write the file
 *   node cv-seed.mjs --check    # fail if the committed file is stale
 *
 * Same contract as `build-workflow.mjs` and `build-evaluate.mjs`: one source of
 * truth, a generated artefact, and a `--check` mode so CI (or a person) can tell
 * that the two agree without writing anything.
 *
 * ⚠️ **`cv-entries.seed.sql` is generated — do not hand-edit it.** An edit there
 * is invisible to `cv.test.js`, which reads the JS, and the next run of this
 * script discards it silently. That is the failure CLAUDE.md records twice (the
 * stale Garmin bridge, the duplicated BIA constants).
 *
 * ## Why the conflict clause updates rather than doing nothing
 *
 * `modules.seed.sql` is `on conflict do nothing`, and MODULES.md documents the
 * consequence at length: once rows exist the file stops being able to change
 * anything, the database becomes the source of truth, and the committed seed
 * rots into a historical document. That was a reasonable call for prose someone
 * edits in place afterwards.
 *
 * It is the wrong call here, because these entries are generated from a
 * committed file that IS the source of truth. `do update` keeps the table
 * tracking the repo, so fixing a typo is a normal edit-and-rerun rather than a
 * hand-written UPDATE nobody reviews. The column list is explicit, so a column
 * added later is not silently reset.
 */

import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

import { CV_ENTRIES } from "./cv-entries.js";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "cv-entries.seed.sql");

/**
 * The owner. Same literal as `modules.seed.sql`, and for the same reason: a
 * seed script runs with no auth session, so `auth.uid()` is null and the
 * SQL-editor idiom in README.md is unavailable here.
 */
const USER_ID = "a33625c2-4dd2-44fa-b2e5-4d455eeac59d";

/**
 * Dollar-quote, so apostrophes in "I've"/"doesn't" never need escaping.
 *
 * ⚠️ Dollar quoting is only safe while the delimiter cannot appear in the value.
 * It cannot today, but "today" is not a guarantee about a file a person edits —
 * and the failure would not be a syntax error, it would be a string that ends
 * early and whatever follows parsed as SQL. Refuse to generate instead.
 */
const DELIM = "$cv$";
const guard = (s) => {
  if (typeof s === "string" && s.includes(DELIM)) {
    throw new Error(
      `entry text contains the dollar-quote delimiter ${DELIM}, which would break out of the literal: ${s.slice(0, 80)}`,
    );
  }
  return s;
};
const q = (s) => (s == null || s === "" ? "null" : `${DELIM}${guard(s)}${DELIM}`);

const textArray = (xs) =>
  !Array.isArray(xs) || xs.length === 0
    ? "'{}'"
    : `array[${xs.map((x) => `${DELIM}${guard(String(x))}${DELIM}`).join(", ")}]`;

const jsonb = (o) =>
  o && Object.keys(o).length > 0
    ? `${DELIM}${guard(JSON.stringify(o))}${DELIM}::jsonb`
    : `'{}'::jsonb`;

const rows = CV_ENTRIES.map((e) => {
  const cells = [
    `'${USER_ID}'`,
    q(e.name),
    q(e.section),
    q(e.title),
    q(e.meta),
    q(e.org),
    q(e.dates),
    q(e.status),
    textArray(e.bullets),
    jsonb(e.data),
    textArray(e.tags),
    q(e.lang ?? "en"),
    e.pinned ? "true" : "false",
    e.enabled === false ? "false" : "true",
    String(Number.isFinite(Number(e.sort)) ? Number(e.sort) : 0),
  ];
  return `  (\n    ${cells.join(",\n    ")}\n  )`;
}).join(",\n");

const sql = `-- cv-entries.seed.sql
-- ===========================================================================
--
-- ⚠️ GENERATED by \`node cv-seed.mjs\` from \`cv-entries.js\`. Do not hand-edit:
-- an edit here is invisible to \`cv.test.js\` (which reads the JS) and the next
-- run of the generator discards it without saying so.
--
-- Every string below is verbatim from \`JobSearch/cv_2026.tex\` (1 Sep 2026).
-- Nothing was written by a model. \`tags\`, \`sort\` and \`pinned\` are the only
-- additions, and they are metadata ABOUT the entries rather than claims made by
-- them.
--
-- Apply \`supabase/migrations/20260908120000_job_cv_entries.sql\` first; this
-- file only fills the table.
--
-- \`do update\` rather than \`do nothing\` — unlike \`modules.seed.sql\`, the
-- source of truth for these rows is the committed \`cv-entries.js\`, so re-running
-- must reconcile the table with the repo rather than silently no-op. See the
-- header of \`cv-seed.mjs\`.

insert into public.job_cv_entries
  (user_id, name, section, title, meta, org, dates, status,
   bullets, data, tags, lang, pinned, enabled, sort)
values
${rows}
on conflict (user_id, lower(name)) do update set
  section = excluded.section,
  title   = excluded.title,
  meta    = excluded.meta,
  org     = excluded.org,
  dates   = excluded.dates,
  status  = excluded.status,
  bullets = excluded.bullets,
  data    = excluded.data,
  tags    = excluded.tags,
  lang    = excluded.lang,
  pinned  = excluded.pinned,
  enabled = excluded.enabled,
  sort    = excluded.sort;
`;

if (process.argv.includes("--check")) {
  if (!existsSync(OUT)) {
    console.error(`missing ${OUT} — run: node cv-seed.mjs`);
    process.exit(1);
  }
  if (readFileSync(OUT, "utf8") !== sql) {
    console.error(`${OUT} is stale — run: node cv-seed.mjs`);
    process.exit(1);
  }
  console.log(`ok — cv-entries.seed.sql matches cv-entries.js (${CV_ENTRIES.length} entries)`);
} else {
  writeFileSync(OUT, sql);
  console.log(`wrote ${OUT} — ${CV_ENTRIES.length} entries`);
}
