name: timetracker-app
options:
  bundleIdPrefix: com.bastianthomsen.timetracker
  deploymentTarget:
    iOS: 14.0
fileGroups: [../../src]
configs:
  debug: debug
  release: release
settingGroups:
  app:
    base:
      PRODUCT_NAME: TimeTracker
      PRODUCT_BUNDLE_IDENTIFIER: com.bastianthomsen.timetracker
targetTemplates:
  app:
    type: application
    sources:
      - path: Sources
    scheme:
      environmentVariables:
        RUST_BACKTRACE: full
        RUST_LOG: info
    settings:
      groups: [app]
targets:
  timetracker-app_iOS:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: ../../ios
        excludes:
          - "SafariBlockerExtension/**"
      - path: Assets.xcassets
      - path: Externals
        excludes:
          - "**/*.a"
      - path: timetracker-app_iOS
      - path: assets
        buildPhase: resources
        type: folder
      - path: LaunchScreen.storyboard
    info:
      path: timetracker-app_iOS/Info.plist
      properties:
        LSRequiresIPhoneOS: true
        UILaunchStoryboardName: LaunchScreen
        UIRequiredDeviceCapabilities: [arm64, metal]
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: "1.0.0"
    entitlements:
      path: timetracker-app_iOS/timetracker-app_iOS.entitlements
    scheme:
      environmentVariables:
        RUST_BACKTRACE: full
        RUST_LOG: info
    settings:
      base:
        ENABLE_BITCODE: false
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        ARCHS: [arm64]
        VALID_ARCHS: arm64
        LIBRARY_SEARCH_PATHS[arch=x86_64]: $(inherited) $(PROJECT_DIR)/Externals/x86_64/$(CONFIGURATION) $(SDKROOT)/usr/lib/swift $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME) $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
        LIBRARY_SEARCH_PATHS[arch=arm64]: $(inherited) $(PROJECT_DIR)/Externals/arm64/$(CONFIGURATION) $(SDKROOT)/usr/lib/swift $(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME) $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)
        ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: true
        EXCLUDED_ARCHS[sdk=iphoneos*]: x86_64
      groups: [app]
    dependencies:
      - framework: libapp.a
        embed: false
      - sdk: CoreGraphics.framework
      - sdk: Metal.framework
      - sdk: MetalKit.framework
      - sdk: QuartzCore.framework
      - sdk: Security.framework
      - sdk: UIKit.framework
      - sdk: WebKit.framework
      - sdk: SafariServices.framework
      - target: timetracker-app_SafariBlocker
        embed: true
    preBuildScripts:
      - script: node tauri ios xcode-script -v --platform ${PLATFORM_DISPLAY_NAME:?} --sdk-root ${SDKROOT:?} --framework-search-paths "${FRAMEWORK_SEARCH_PATHS:?}" --header-search-paths "${HEADER_SEARCH_PATHS:?}" --gcc-preprocessor-definitions "${GCC_PREPROCESSOR_DEFINITIONS:-}" --configuration ${CONFIGURATION:?} ${FORCE_COLOR} ${ARCHS:?}
        name: Build Rust Code
        basedOnDependencyAnalysis: false
        outputFiles:
          - $(SRCROOT)/Externals/x86_64/${CONFIGURATION}/libapp.a
          - $(SRCROOT)/Externals/arm64/${CONFIGURATION}/libapp.a

  timetracker-app_SafariBlocker:
    type: app-extension
    platform: iOS
    sources:
      - path: ../../ios/SafariBlockerExtension
        excludes:
          - "Info.plist"
          - "blockerList.json"
      - path: ../../ios/SafariBlockerExtension/blockerList.json
        buildPhase: resources
    dependencies:
      - sdk: SafariServices.framework
      - sdk: WebKit.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.bastianthomsen.timetracker.SafariBlocker
        DEVELOPMENT_TEAM: G9D6JYJSLT
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        ARCHS: [arm64]
        VALID_ARCHS: arm64
        IPHONEOS_DEPLOYMENT_TARGET: "14.0"
        INFOPLIST_FILE: $(SRCROOT)/../../ios/SafariBlockerExtension/Info.plist
        CODE_SIGN_ENTITLEMENTS: $(SRCROOT)/../../ios/SafariBlockerExtension/SafariBlocker.entitlements