mod commands;
mod db;
mod models;

use std::sync::Mutex;
use tauri::Manager;

pub struct AppState {
    pub db: Mutex<rusqlite::Connection>,
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .setup(|app| {
            let app_dir = app.path().app_data_dir()?;
            std::fs::create_dir_all(&app_dir)?;
            let db_path = app_dir.join("pathfinder.db");
            let conn = rusqlite::Connection::open(&db_path).expect("failed to open database");
            db::init(&conn).expect("failed to init database schema");
            app.manage(AppState { db: Mutex::new(conn) });
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            commands::get_goals,
            commands::create_goal,
            commands::update_goal,
            commands::delete_goal,
            commands::get_goal_groups,
            commands::create_goal_group,
            commands::update_goal_group,
            commands::delete_goal_group,
            commands::get_plans,
            commands::create_plan,
            commands::update_plan,
            commands::delete_plan,
            commands::get_tasks,
            commands::get_all_tasks,
            commands::create_task,
            commands::update_task,
            commands::toggle_task,
            commands::delete_task,
            commands::set_task_kanban_status,
            commands::get_project_goals,
            commands::add_project_goal,
            commands::toggle_project_goal,
            commands::delete_project_goal,
            commands::get_systems,
            commands::create_system,
            commands::update_system,
            commands::delete_system,
            commands::mark_system_done,
            commands::unmark_system_done,
            commands::get_system_subtasks,
            commands::add_system_subtask,
            commands::delete_system_subtask,
            commands::toggle_system_subtask,
            commands::get_today_focus,
            commands::search,
            commands::get_week_items,
            commands::get_time_blocks,
            commands::save_time_block,
            commands::get_routines,
            commands::toggle_routine,
            commands::add_routine_item,
            commands::delete_routine_item,
            commands::get_daily_plan,
            commands::toggle_daily_completion,
            commands::create_daily_section,
            commands::update_daily_section,
            commands::delete_daily_section,
            commands::create_daily_item,
            commands::update_daily_item,
            commands::delete_daily_item,
            commands::get_reminders,
            commands::add_reminder,
            commands::toggle_reminder,
            commands::delete_reminder,
            commands::get_quick_notes,
            commands::add_quick_note,
            commands::delete_quick_note,
            commands::get_brain_dump,
            commands::add_brain_entry,
            commands::delete_brain_entry,
            commands::get_events,
            commands::add_event,
            commands::delete_event,
            commands::get_deadlines,
            commands::add_deadline,
            commands::toggle_deadline,
            commands::delete_deadline,
            commands::get_agreements,
            commands::add_agreement,
            commands::delete_agreement,
            commands::get_daily_goals,
            commands::set_daily_primary_goal,
            commands::clear_daily_primary_goal,
            commands::add_daily_secondary_goal,
            commands::delete_daily_secondary_goal,
            commands::get_cal_blocks,
            commands::create_cal_block,
            commands::update_cal_block,
            commands::delete_cal_block,
            commands::get_journal_entry,
            commands::save_journal_entry,
            commands::create_recurring_cal_block,
            commands::update_recurring_cal_block,
            commands::delete_recurring_cal_block,
            commands::get_course_assignments,
            commands::create_course_assignment,
            commands::update_course_assignment,
            commands::delete_course_assignment,
            commands::get_ca_subtasks,
            commands::add_ca_subtask,
            commands::toggle_ca_subtask,
            commands::delete_ca_subtask,
            commands::export_data,
            commands::get_db_path,
            commands::get_lifestyle_areas,
            commands::create_lifestyle_area,
            commands::update_lifestyle_area,
            commands::delete_lifestyle_area,
            commands::get_lifestyle_items,
            commands::get_pipeline_templates,
            commands::create_pipeline_template,
            commands::update_pipeline_template,
            commands::delete_pipeline_template,
            commands::upsert_pipeline_steps,
            commands::get_pipeline_runs,
            commands::create_pipeline_run,
            commands::update_pipeline_run,
            commands::delete_pipeline_run,
            commands::toggle_pipeline_run_step,
            commands::update_pipeline_run_step,
            commands::get_pipeline_step_subtasks,
            commands::add_pipeline_step_subtask,
            commands::toggle_pipeline_step_subtask,
            commands::delete_pipeline_step_subtask,
            commands::get_games,
            commands::create_game,
            commands::update_game,
            commands::delete_game,
            commands::get_game_features,
            commands::create_game_feature,
            commands::update_game_feature,
            commands::set_game_feature_status,
            commands::delete_game_feature,
            commands::get_game_devlog,
            commands::add_game_devlog_entry,
            commands::delete_game_devlog_entry,
            commands::get_habits_for_date,
            commands::create_daily_habit,
            commands::delete_daily_habit,
            commands::toggle_habit_completion,
            commands::get_run_logs,
            commands::create_run_log,
            commands::delete_run_log,
            commands::get_workout_logs,
            commands::create_workout_log,
            commands::delete_workout_log,
            commands::add_workout_exercise,
            commands::delete_workout_exercise,
            commands::get_roadmap_items,
            commands::create_roadmap_item,
            commands::update_roadmap_item,
            commands::delete_roadmap_item,
            commands::set_roadmap_item_status,
            commands::get_course_books,
            commands::create_course_book,
            commands::update_course_book,
            commands::delete_course_book,
            commands::add_book_reading_log,
            commands::delete_book_reading_log,
            commands::upsert_book_sections,
            commands::toggle_book_section,
            commands::update_book_section,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
