-- Learn (lr_) schema: LearnAndRetain concept-graph learning system, migrated
-- into the NEXUS project. See apps/NexusLocal/LEARN_PLAN.md for the full spec.
-- Posture matches the productivity stack: user_id text default 'default',
-- RLS enabled with permissive anon policies (tighten via the auth playbook later).

-- ── Concept DAG ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS lr_course (
  c_id   bigint PRIMARY KEY,
  title  text,
  active boolean DEFAULT true
);

CREATE TABLE IF NOT EXISTS lr_topic (
  t_id  bigint PRIMARY KEY,
  c_id  bigint REFERENCES lr_course(c_id),
  title text
);

CREATE TABLE IF NOT EXISTS lr_concept (
  concept_id  text PRIMARY KEY,
  t_id        bigint REFERENCES lr_topic(t_id),
  title       text,
  kind        text,
  role        text DEFAULT 'concept',
  description text,
  proof       text,
  source_ref  text,
  item_type   text
);

CREATE TABLE IF NOT EXISTS lr_concept_prereq (
  prereq_id  text NOT NULL REFERENCES lr_concept(concept_id),
  concept_id text NOT NULL REFERENCES lr_concept(concept_id),
  PRIMARY KEY (prereq_id, concept_id)
);

-- ── Linearized path ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS lr_unit (
  unit_id   bigint PRIMARY KEY,
  course_id bigint REFERENCES lr_course(c_id),
  idx       integer NOT NULL,
  code      text NOT NULL,
  title     text,
  sections  text[]
);

CREATE TABLE IF NOT EXISTS lr_unit_concept (
  unit_id    bigint NOT NULL REFERENCES lr_unit(unit_id),
  concept_id text   NOT NULL REFERENCES lr_concept(concept_id),
  ord        integer,
  PRIMARY KEY (unit_id, concept_id)
);

CREATE TABLE IF NOT EXISTS lr_unit_progress (
  user_id     text NOT NULL DEFAULT 'default',
  unit_id     bigint NOT NULL REFERENCES lr_unit(unit_id),
  status      text NOT NULL DEFAULT 'locked',  -- locked | in_progress | mastered
  mastered_at timestamptz,
  updated_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, unit_id)
);

-- ── Problem bank (authoring grounding + capstones) ─────────────────────────
CREATE TABLE IF NOT EXISTS lr_item (
  item_id    bigint PRIMARY KEY,
  slug       text UNIQUE,
  title      text,
  year       integer,
  difficulty integer,
  format     text,  -- written | multiple_choice | flashcard | programming | example
  prompt     text,
  source_ref text
);

CREATE TABLE IF NOT EXISTS lr_written_item (
  item_id  bigint PRIMARY KEY REFERENCES lr_item(item_id),
  solution text
);

CREATE TABLE IF NOT EXISTS lr_mcq_option (
  option_id  bigint PRIMARY KEY,
  item_id    bigint REFERENCES lr_item(item_id),
  body       text,
  is_correct boolean
);

CREATE TABLE IF NOT EXISTS lr_qmatrix (
  item_id    bigint NOT NULL REFERENCES lr_item(item_id),
  concept_id text   NOT NULL REFERENCES lr_concept(concept_id),
  weight     double precision,
  PRIMARY KEY (item_id, concept_id)
);

-- ── Crafted unit content (the crown) ───────────────────────────────────────
CREATE TABLE IF NOT EXISTS lr_unit_content (
  unit_id     bigint NOT NULL REFERENCES lr_unit(unit_id),
  version     integer NOT NULL DEFAULT 1,
  status      text NOT NULL DEFAULT 'draft',  -- draft | approved | live
  content     jsonb NOT NULL,
  authored_by text,
  notes       text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (unit_id, version)
);

-- ── Learner state ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS lr_memory_state (
  user_id       text NOT NULL DEFAULT 'default',
  concept_id    text NOT NULL REFERENCES lr_concept(concept_id),
  value_alpha   double precision NOT NULL DEFAULT 1.0,
  value_beta    double precision NOT NULL DEFAULT 1.0,
  heat          double precision NOT NULL DEFAULT 0.0,
  lens_counts   jsonb NOT NULL DEFAULT '{}'::jsonb,  -- {"row": n, "matrix": n, "column": n}
  last_reviewed timestamptz NOT NULL DEFAULT now(),
  last_decayed  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, concept_id)
);

CREATE TABLE IF NOT EXISTS lr_attempt_log (
  a_id     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id  text NOT NULL DEFAULT 'default',
  item_ref text,      -- lr_item.slug or a lr_unit_content drill id
  lens     text,      -- row | matrix | column
  grade    integer,   -- 0 don't-know | 1 hard | 2 normal | 3 easy
  at       timestamptz NOT NULL DEFAULT now()
);

-- Server-computed verdict row (blocking_state pattern). Deliberately NOT
-- seeded: a missing row means "never computed", which is different from
-- "computed, nothing due". Clients keep last known state on missing/failed.
CREATE TABLE IF NOT EXISTS lr_learn_state (
  user_id           text PRIMARY KEY DEFAULT 'default',
  due_concepts      jsonb,
  frontier_units    jsonb,
  streak_days       integer,
  last_session_date date,
  computed_at       timestamptz
);

-- Single source of truth for graduation into the retention space.
CREATE OR REPLACE VIEW lr_retained_concept AS
  SELECT up.user_id, uc.concept_id
  FROM lr_unit_concept uc
  JOIN lr_unit_progress up
    ON up.unit_id = uc.unit_id AND up.status = 'mastered';

-- ── RLS: permissive anon (matches productivity-stack posture) ──────────────
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'lr_course','lr_topic','lr_concept','lr_concept_prereq',
    'lr_unit','lr_unit_concept','lr_unit_progress',
    'lr_item','lr_written_item','lr_mcq_option','lr_qmatrix',
    'lr_unit_content','lr_memory_state','lr_attempt_log','lr_learn_state'
  ] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies WHERE schemaname = 'public'
        AND tablename = t AND policyname = 'anon_all'
    ) THEN
      EXECUTE format(
        'CREATE POLICY anon_all ON %I FOR ALL USING (true) WITH CHECK (true)', t
      );
    END IF;
  END LOOP;
END $$;
