-- Infinite exercises: per-item learner feedback (append-only log).
-- See apps/NexusLocal/LEARN_PLAN.md "Infinite exercises". Either broken flag
-- excludes the item from future shuffles for that user.
CREATE TABLE IF NOT EXISTS lr_item_feedback (
  fb_id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id         text NOT NULL DEFAULT 'default',
  item_id         bigint NOT NULL REFERENCES lr_item(item_id),
  difficulty      integer,                       -- 1 let | 2 mellem | 3 svær
  understood      boolean,
  exercise_broken boolean NOT NULL DEFAULT false,
  solution_broken boolean NOT NULL DEFAULT false, -- broken or vague
  note            text,
  at              timestamptz NOT NULL DEFAULT now()
);

DO $$
BEGIN
  EXECUTE 'ALTER TABLE lr_item_feedback ENABLE ROW LEVEL SECURITY';
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public'
      AND tablename = 'lr_item_feedback' AND policyname = 'anon_all'
  ) THEN
    EXECUTE 'CREATE POLICY anon_all ON lr_item_feedback FOR ALL USING (true) WITH CHECK (true)';
  END IF;
END $$;
