-- The lr_ port created plain bigint PKs where the old LearnAndRetain tables
-- had serials — pipeline inserts without explicit ids fail 23502. Add
-- identities, park sequences past current max. Applied live 2026-09-03.
ALTER TABLE lr_topic ALTER COLUMN t_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE lr_item ALTER COLUMN item_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE lr_mcq_option ALTER COLUMN option_id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE lr_unit ALTER COLUMN unit_id ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('lr_topic','t_id'), (SELECT COALESCE(MAX(t_id),0)+1 FROM lr_topic), false);
SELECT setval(pg_get_serial_sequence('lr_item','item_id'), (SELECT COALESCE(MAX(item_id),0)+1 FROM lr_item), false);
SELECT setval(pg_get_serial_sequence('lr_mcq_option','option_id'), (SELECT COALESCE(MAX(option_id),0)+1 FROM lr_mcq_option), false);
SELECT setval(pg_get_serial_sequence('lr_unit','unit_id'), (SELECT COALESCE(MAX(unit_id),0)+1 FROM lr_unit), false);
