-- Restore pf_reminders, reverting the drop in 20260821120000.
--
-- The drop was wrong, and the reason is worth writing down because it applies to
-- every future schema removal in this repo:
--
--   **The database is shared between the deployed app and every branch.**
--
-- `main` is what Vercel serves. main's `getReminders()` ends with
-- `if (error) err(error)`, and the dashboard calls it inside a `Promise.all` —
-- so a missing table does not degrade, it rejects the whole dashboard load. The
-- table being *empty* was never the relevant fact; the relevant fact was that
-- deployed code still queried it.
--
-- The general rule: a schema removal may only be applied AFTER the code that
-- stops reading it is deployed, never alongside it. Additive changes are safe in
-- either order — which is why the other four migrations in this series caused no
-- trouble — but removals are strictly ordered.
--
-- Recreated with its original shape (`due_date` nullable, unlike pf_deadlines)
-- and the same owner_all policy as every other pf_ table. It stays empty; the
-- real reminders are quick tasks (`pf_tasks.category = 'reminder'`).
--
-- To finish the removal: merge and deploy the branch that stops reading it, then
-- re-apply 20260821120000_drop_pf_reminders.sql, whose row-count guard still
-- protects against dropping data.

create table if not exists public.pf_reminders (
  id         bigint generated by default as identity primary key,
  user_id    text        not null default 'default',
  title      text        not null,
  due_date   text,
  done       boolean     not null default false,
  created_at timestamptz not null default now()
);

alter table public.pf_reminders enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where tablename = 'pf_reminders' and policyname = 'owner_all'
  ) then
    create policy owner_all on public.pf_reminders
      for all
      using (user_id = (select (auth.uid())::text))
      with check (user_id = (select (auth.uid())::text));
  end if;
end $$;
