-- Generalprøve: reference exam dispositions + rehearsal run log.
-- See apps/NexusLocal/LEARN_PLAN.md "Generalprøve — the final canvas node
-- (pinned)". lr_disposition.content is JSONB: { beats: [{ order, title,
-- concept_ids, statement_titles, notes_md }] } — the ordered presentation
-- beats of one official exam disposition, authored from
-- LinAlgContext/dispositioner.md via the usual author → verify → draft →
-- Godkend pipeline (status mirrors lr_proof_content's ladder).
-- lr_rehearsal_run mirrors lr_challenge_run's posture: one row per round,
-- scores are JSONB so P2/P3 can evolve the report without DDL.
CREATE TABLE IF NOT EXISTS lr_disposition (
  disposition_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id      bigint NOT NULL,
  code           text UNIQUE NOT NULL,   -- e.g. 'la-disp-4'
  title          text NOT NULL,
  status         text NOT NULL DEFAULT 'draft',  -- draft | approved | live
  content        jsonb NOT NULL,
  authored_by    text,
  notes          text,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS lr_rehearsal_run (
  run_id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id        text NOT NULL DEFAULT 'default',
  disposition_id bigint NOT NULL REFERENCES lr_disposition(disposition_id),
  started_at     timestamptz NOT NULL DEFAULT now(),
  duration_secs  integer,
  scores         jsonb,   -- { coverage, order, links, missed: [], extra: [] }
  coach_line     text
);

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['lr_disposition','lr_rehearsal_run'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies WHERE schemaname = 'public'
        AND tablename = t AND policyname = 'anon_all'
    ) THEN
      EXECUTE format('CREATE POLICY anon_all ON %I FOR ALL USING (true) WITH CHECK (true)', t);
    END IF;
  END LOOP;
END $$;
