-- Learn ecosystem: tracked study materials, progress events, and the composed
-- daily plan. This is the data model behind "every day: an intro brief, a 90-
-- minute reading, the personalised lesson, and a spaced-repetition session",
-- with the plan fanned out into PathFinder tasks and a Vault daily note by the
-- `learn-plan` edge function (pg_cron — it must run while every device sleeps).
--
-- RLS: `anon_all`, matching the whole lr_ family (the Learn app reads lr_
-- tables with the anon client by design — see NexusLocal learn/api.ts). These
-- tables migrate to auth.uid() together with the rest of the family in
-- SECURITY_RLS_MIGRATION.md; adding a lone auth-scoped island here would make
-- the Learn surfaces read empty sets instead.

create table if not exists lr_materials (
  id uuid primary key default gen_random_uuid(),
  user_id text not null default 'default',
  kind text not null default 'book' check (kind in ('book','document','paper','assignment','course','lesson')),
  title text not null,
  -- Where the material LIVES: a Vault node (parsed book / PDF / note) and/or
  -- an lr_course. Both nullable — an assignment may be neither.
  vault_node_id text,
  course_id bigint,
  pf_plan_id bigint,
  url text,   -- external surface (a lesson artifact) when the material is not a Vault node
  unit_label text not null default 'pages',
  total_units numeric,          -- null = unknown length; progress is absolute
  start_unit numeric not null default 0,  -- front matter offset (reading starts after it)
  pace_units_per_min numeric not null default 0.15, -- fallback until events measure it
  priority numeric not null default 1,
  status text not null default 'active' check (status in ('active','paused','done')),
  due_date date,
  notes text,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create table if not exists lr_progress_events (
  id bigint generated by default as identity primary key,
  user_id text not null default 'default',
  material_id uuid not null references lr_materials(id) on delete cascade,
  event_date date not null default (now() at time zone 'Europe/Copenhagen')::date,
  kind text not null default 'reading' check (kind in ('reading','exercise','lesson','review','baseline','other')),
  -- Absolute positions when known (pages), else just a delta. ⚠️ Absent is
  -- not zero: units_delta null means "worked, amount unmeasured" and every
  -- consumer must skip it in sums rather than count 0.
  units_from numeric,
  units_to numeric,
  units_delta numeric,
  minutes integer,
  note text,
  source text not null default 'manual',
  created_at timestamptz not null default now()
);
create index if not exists lr_progress_events_material_idx
  on lr_progress_events (material_id, event_date desc);
create index if not exists lr_progress_events_user_date_idx
  on lr_progress_events (user_id, event_date desc);

-- One composed row per (user, day). ⚠️ Deliberately never seeded: a missing
-- row means "no plan computed", which is different from "rest day" — the
-- blocking_state rule. The generator aborts before writing on any read
-- failure, so a row that exists was built from a complete picture.
create table if not exists lr_daily_plan (
  user_id text not null default 'default',
  plan_date date not null,
  blocks jsonb not null,
  brief_md text not null,
  pf_task_ids jsonb not null default '[]',
  vault_note_id text,
  status text not null default 'ready' check (status in ('ready','done')),
  generated_at timestamptz not null default now(),
  completed_at timestamptz,
  primary key (user_id, plan_date)
);

create table if not exists lr_learn_settings (
  user_id text primary key default 'default',
  reading_minutes integer not null default 90,
  lesson_minutes integer not null default 45,
  review_minutes integer not null default 15,
  intro_minutes integer not null default 10,
  lesson_artifact_url text,
  -- PathFinder / Vault fan-out targets. auth uid + node ids, NOT 'default':
  -- pf_tasks and vault_* are real-auth tables.
  pf_user_id text,
  pf_plan_id bigint,
  vault_user_id text,
  vault_folder_id text
);

do $$ begin
  if not exists (select 1 from pg_policies where tablename = 'lr_materials') then
    create policy anon_all on lr_materials for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'lr_progress_events') then
    create policy anon_all on lr_progress_events for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'lr_daily_plan') then
    create policy anon_all on lr_daily_plan for all using (true) with check (true);
  end if;
  if not exists (select 1 from pg_policies where tablename = 'lr_learn_settings') then
    create policy anon_all on lr_learn_settings for all using (true) with check (true);
  end if;
end $$;

alter table lr_materials enable row level security;
alter table lr_progress_events enable row level security;
alter table lr_daily_plan enable row level security;
alter table lr_learn_settings enable row level security;
