-- Lynudfordring: persisted timed-challenge runs.
-- See apps/NexusLocal/LEARN_PLAN.md "Lynudfordring — timed challenge".
CREATE TABLE IF NOT EXISTS lr_challenge_run (
  run_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       text NOT NULL DEFAULT 'default',
  score         integer NOT NULL,
  correct       integer NOT NULL,
  total         integer NOT NULL,
  best_streak   integer,
  duration_secs integer,
  rounds        jsonb,           -- [{round, label, score, correct, total}]
  at            timestamptz NOT NULL DEFAULT now()
);

DO $$
BEGIN
  EXECUTE 'ALTER TABLE lr_challenge_run ENABLE ROW LEVEL SECURITY';
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public'
      AND tablename = 'lr_challenge_run' AND policyname = 'anon_all'
  ) THEN
    EXECUTE 'CREATE POLICY anon_all ON lr_challenge_run FOR ALL USING (true) WITH CHECK (true)';
  END IF;
END $$;
