-- Sprint: bucketed fast-feedback exam training (DBMS pilot).
-- See apps/NexusLocal/LEARN_PLAN.md "Sprint — bucketed fast-feedback exam
-- training (pinned, 2026-08-18)". One row per fast-format drill derived
-- from an exam part (source_slug → lr_item.slug) or emitted by a
-- permutation generator (source_slug NULL, authored_by 'generator:<x>').
-- content jsonb shape depends on format (mcq | truefalse | blank | tiles
-- | why) — every shape carries why_md + how_md + tip_md. Per-bucket stats
-- come from lr_attempt_log joined on code; no separate stats table.
CREATE TABLE IF NOT EXISTS lr_sprint_drill (
  drill_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id   bigint NOT NULL,
  bucket      text NOT NULL,
  code        text UNIQUE NOT NULL,   -- e.g. 'spr-dbms-ra-012'
  source_slug text,                   -- lr_item.slug or NULL for generated
  format      text NOT NULL,          -- mcq | truefalse | blank | tiles | why
  content     jsonb NOT NULL,
  status      text NOT NULL DEFAULT 'draft',  -- draft | approved | live
  authored_by text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS lr_sprint_drill_bucket_idx
  ON lr_sprint_drill (course_id, bucket);

DO $$
BEGIN
  EXECUTE 'ALTER TABLE lr_sprint_drill ENABLE ROW LEVEL SECURITY';
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname = 'public'
      AND tablename = 'lr_sprint_drill' AND policyname = 'anon_all'
  ) THEN
    EXECUTE 'CREATE POLICY anon_all ON lr_sprint_drill FOR ALL USING (true) WITH CHECK (true)';
  END IF;
END $$;
