-- Proof side-paths: optional proof units branching off mastered modules.
-- See apps/NexusLocal/LEARN_PLAN.md "Proof side-paths (pinned)". Content is
-- UnitContent-shaped JSONB (the Player renders it); completing a proof unit
-- writes lr_proof_progress only — never lr_unit_progress / retention.
CREATE TABLE IF NOT EXISTS lr_proof_unit (
  proof_id       bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_unit_id bigint NOT NULL REFERENCES lr_unit(unit_id),
  code           text UNIQUE NOT NULL,   -- e.g. 'la_2_u1-proofs'
  title          text
);

CREATE TABLE IF NOT EXISTS lr_proof_content (
  proof_id    bigint NOT NULL REFERENCES lr_proof_unit(proof_id),
  version     integer NOT NULL DEFAULT 1,
  status      text NOT NULL DEFAULT 'draft',  -- draft | approved | live
  content     jsonb NOT NULL,
  authored_by text,
  notes       text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (proof_id, version)
);

CREATE TABLE IF NOT EXISTS lr_proof_progress (
  user_id      text NOT NULL DEFAULT 'default',
  proof_id     bigint NOT NULL REFERENCES lr_proof_unit(proof_id),
  status       text NOT NULL DEFAULT 'available',  -- available | in_progress | completed
  completed_at timestamptz,
  updated_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, proof_id)
);

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['lr_proof_unit','lr_proof_content','lr_proof_progress'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    IF NOT EXISTS (
      SELECT 1 FROM pg_policies WHERE schemaname = 'public'
        AND tablename = t AND policyname = 'anon_all'
    ) THEN
      EXECUTE format('CREATE POLICY anon_all ON %I FOR ALL USING (true) WITH CHECK (true)', t);
    END IF;
  END LOOP;
END $$;
